## **Part I (Warm Up):**



Q1: Write a Python function that takes an array of integers as an argument and
returns a new array containing only the odd numbers in the original array.


In [25]:
import numpy as np
def odd_number(array):
  for number in array:
    if number % 2 == 1:
      print(number)
#Let's take one example
example_array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])
odd_number(example_array)

1
3
5
7
9
11
13
15
17
19


Q2: Create a class called Dog with attributes name and breed. Add a method called
bark that prints a message with the dog's name and a barking sound.


In [27]:
class dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} barks bhav bhav!")
#Let's take one example
dog("Tommy", "German Shepherd").bark()

Tommy barks bhav bhav!


Q3. Write a Python program that creates a numpy array of 100 random integers
between 0 and 100, and prints any 2 measures of central tendency and 2 measures
of spread of the array.


In [38]:
import random
x = np.random.randint(low=0, high=100, size = 100)
x

array([72, 78, 39, 54, 57, 50, 74, 61, 33, 98,  5, 18, 55, 17, 78, 82, 74,
       94, 49, 66, 95, 97, 59, 26,  8, 88, 98, 98, 42, 27,  3, 27, 35, 67,
        2, 23, 16, 52, 27, 17,  1, 26, 14, 25, 41, 41,  6, 91, 45, 94, 10,
       83, 12, 70, 78,  9,  7, 60, 43, 62, 39, 38, 25, 65, 63, 51, 73, 55,
       59, 73, 65, 93, 78, 25, 64,  4, 35, 33, 14, 77, 50,  1, 61, 27, 72,
       48, 95, 81, 40, 37, 37, 43, 75, 25, 51, 72, 27, 15, 19, 45])

In [39]:
sum = 0
for i in range(100):
  sum += x[i]
mean = sum/100
print(mean)

48.29


In [44]:
x.sort()
x

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 14, 14, 15, 16, 17,
       17, 18, 19, 23, 25, 25, 25, 25, 26, 26, 27, 27, 27, 27, 27, 33, 33,
       35, 35, 37, 37, 38, 39, 39, 40, 41, 41, 42, 43, 43, 45, 45, 48, 49,
       50, 50, 51, 51, 52, 54, 55, 55, 57, 59, 59, 60, 61, 61, 62, 63, 64,
       65, 65, 66, 67, 70, 72, 72, 72, 73, 73, 74, 74, 75, 77, 78, 78, 78,
       78, 81, 82, 83, 88, 91, 93, 94, 94, 95, 95, 97, 98, 98, 98])

In [45]:
median = (x[49]+x[50])/2
median

48.5

In [46]:
range = x[99]-x[0]
range

97

In [49]:
standard_deviation = x.std()
standard_deviation

27.85724142839704

## **PART II (Mandatory) :**

Q1. Create a class which defines an __init__ function that initializes the class
attribute array. Define another function get_array which takes inputs for the
length of the array and inputs all the elements, and returns its corresponding sorted
array.


In [50]:
class Array:
    def __init__(self):
        self.array = []

    def get_array(self, length):
      for i in range(length):
        number = input("Enter number:")
        self.array.append(number)
      self.array.sort()
      return self.array

Q2.
A. Create a 2D array of size 4*4 using list and perform the following
operations:
1. extract the diagonal elements from the array
2. Find the trace of the Matrix
3. Find the max and min element of each row in that matrix

In [87]:
x = np.empty([4,4], dtype=int)
x

array([[       55344752,               0,            1857,
               50699142],
       [139810698157592, 139810698157592, 139810698157592,
        139810698157592],
       [              0,               1,      4345666304,
                      5],
       [139814070386687,              33,        51048032,
               48207408]])

In [88]:
x[0][0]

55344752

In [89]:
x[1][1]

139810698157592

In [90]:
x[2][2]

4345666304

In [91]:
x[3][3]

48207408

In [92]:
trace = x[0][0] + x[1][1] + x[2][2] + x[3][3]
trace

139815147376056

In [106]:
x.sort()
x

array([[              0,            1857,        50699142,
               55344752],
       [139810698157592, 139810698157592, 139810698157592,
        139810698157592],
       [              0,               1,               5,
             4345666304],
       [             33,        48207408,        51048032,
        139814070386687]])

In [108]:
max_row1 = x[0][3]
max_row1

55344752

In [109]:
min_row1 = x[0][0]
min_row1

0

In [110]:
max_row2 = x[1][3]
max_row2

139810698157592

In [111]:
min_row1 = x[1][0]
min_row1

139810698157592

In [112]:
max_row3 = x[2][3]
max_row3

4345666304

In [113]:
min_row3 = x[2][0]
min_row3

0

In [114]:
max_row4 = x[3][3]
max_row4

139814070386687

In [115]:
min_row4 = x[3][0]
min_row4

33

B. Create another 2D numpy array with shape (4, 5) where each element of the
array is a random float between 0 and 1, inclusive, using numpy's uniform
distribution function. Print the resulting numpy array.


In [116]:
y = np.random.uniform(low=0, high=1, size=(4, 4))
y

array([[0.66567921, 0.43804099, 0.14862496, 0.11059505],
       [0.55025772, 0.51904993, 0.89998153, 0.30892121],
       [0.23159149, 0.51818962, 0.54458428, 0.68040039],
       [0.5537885 , 0.49035542, 0.28914178, 0.78418144]])

C. Multiply the numpy arrays created in Part A and Part B element-wise, and
print the resulting numpy array.

In [118]:
c = np.dot(x, y)
c

array([[4.23917986e+07, 5.34113319e+07, 4.36141074e+07, 7.78966169e+07],
       [2.79805516e+14, 2.74816936e+14, 2.63170229e+14, 2.63417069e+14],
       [2.40658002e+09, 2.13092101e+09, 1.25651370e+09, 3.40779087e+09],
       [7.74274624e+13, 6.85586381e+13, 4.04261606e+13, 1.09639649e+14]])

Q3. Write a program that reads in the CSV file containing data on stock prices
(including date, open price, high price, low price, closing price, and volume) and
creates a pandas dataframe with the data. Then, use numpy to calculate the average
closing price for each month and print the results.


In [135]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Data - STOCK_US_XNYS_CSV.csv')
data.head(252)

Date   Open   High    Low  Close   Volume
0    05/05/2023  26.93  27.71  26.59  27.59  146,854
1    05/04/2023  29.17  29.17  26.12  26.74  187,882
2    05/03/2023  29.00  29.36  27.83  28.09  138,729
3    05/02/2023  29.39  29.39  28.47  28.96  132,896
4    05/01/2023  28.80  29.74  28.80  29.69   58,964
..          ...    ...    ...    ...    ...      ...
247  05/11/2022  39.59  40.70  38.90  38.99  212,540
248  05/10/2022  40.23  40.97  39.15  39.29  263,363
249  05/09/2022  40.67  40.80  39.50  40.07  171,351
250  05/06/2022  41.33  41.53  40.22  41.30  112,366
251  05/05/2022  42.81  42.95  40.88  41.49   85,554

[252 rows x 6 columns]

In [150]:
import numpy
df = pd.DataFrame(data)
a = df.to_numpy()
a

array([['05/05/2023', 26.93, 27.71, 26.59, 27.59, '146,854'],
       ['05/04/2023', 29.17, 29.17, 26.12, 26.74, '187,882'],
       ['05/03/2023', 29.0, 29.36, 27.83, 28.09, '138,729'],
       ...,
       ['05/09/2022', 40.67, 40.8, 39.5, 40.07, '171,351'],
       ['05/06/2022', 41.33, 41.53, 40.22, 41.3, '112,366'],
       ['05/05/2022', 42.81, 42.95, 40.88, 41.49, '85,554']], dtype=object)

In [154]:
#Average of May 2023
sum = a[0][4]+a[1][4]+a[2][4]+a[3][4]+a[4][4]
mean = sum/5
mean

28.214

Similarily for other month we can calculate its closing average. I wanted to use for loop which will make it easy to write but I dont know why its giving me error for some reason. I used for loop in numpy for above problem 3 in part 1 and its working there and its not working here. So please consider.